### ISSUE TITLE
Casebook creation for suspicious email 

### ISSUE THREAD

**Issue by tekgourou** [CiscoSecurity/sxo-05-security-workflows#11]
Hi

I suggest that a detection of suspicious email also create a casebook so security analyst have something to start with in SecureX. thanks.

**Comment by mavander** [comment]
Hi @tekgourou -
We're not going to add automatic casebook creation to the workflow at this time. You can certainly add the `Threat Response v2 - Create Casebook` atomic to your workflow if you feel a casebook is useful. You can also create a casebook in the SecureX ribbon and link it to the incident generated by the workflow.
Thanks for the suggestions!
-Matt
