### ISSUE TITLE
Trigger Status stuck in "Update-in-Progress"

### ISSUE THREAD

**Issue by jeiband** [CiscoSecurity/sxo-05-security-workflows#112]
On the last 3 workflows, I have either enabled an existing Trigger or added one.  They all seem to stay in the update-in-progress status.....  Any ideas how to correct or what could be wrong?

Workflows:
0001 - Talos - Get New Blog Posts
0012 - Secure Endpoint - Threat Hunting Events to Incidents
0010B - Phishing Investigation - Statistics

Thanks!

**Comment by mavander** [comment]
Hi-
Unfortunately, I can't provide technical support for the SecureX product through GitHub. If you're experiencing an issue with the product, please open a case with Cisco TAC.
-Matt
