### ISSUE TITLE
Workflow fails at the 500th iteration using the For Loop.

### ISSUE THREAD

**Issue by SecOp187** [CiscoSecurity/sxo-05-security-workflows#150]
I use a for loop to iterate over a table that has more than 500 rows. My workflow keeps failing after processing the 500th iteration. Please advise.

**Comment by mavander** [comment]
Hello-

There is a limit of 500 iterations built into SecureX orchestration for loops. This is defined by the `AO_LOOP_LIMIT` global variable and can't be changed. Some people get around the loop limit by putting loops inside of loops or passing large sets of data to Python for processing.

-Matt
