### ISSUE TITLE
error: No JWT found in HTTP Authorization header

### ISSUE THREAD

**Issue by sneekysob** [CiscoSecurity/sxo-05-security-workflows#153]
running workflow **0001 - Talos - Get New Blog Posts** and fails during the For Each Post
Current Item: {"link":"http://blog.talosintelligence.com/2022/04/threat-roundup-0401-0408.html","pubDate":"Fri, 08 Apr 2022 14:48:42 PDT","title":"Threat Roundup for April 1 to April 8"}
Error Code: 400
Error Message: 
error: Failed to inspect content

Status code: 401
Response body: {"error":"invalid_request","error_description":"No JWT found in HTTP Authorization header"}

**Comment by mavander** [comment]
Hi @sneekysob -
It looks like one of the `Threat Response` activities is failing because an access token is missing. If you want help troubleshooting this, you'll need to provide more information about which activity is failing in the workflow and how that activity is configured.
-Matt

**Comment by mavander** [comment]
Closed due to inactivity

**Comment by sneekysob** [comment]
Hi @mavander ,

My apologies for not replying sooner - you were correct, the access token was changed by someone and was not documented. Thanks for your time. 

Cheers!
