### ISSUE TITLE
Phishing workflow fails at get samples by file hash atomic

### ISSUE THREAD

**Issue by nedsilva1** [CiscoSecurity/sxo-05-security-workflows#173]
<img width="1433" alt="Screen Shot 2022-07-05 at 9 18 13 AM" src="https://user-images.githubusercontent.com/108752473/177375737-6da3e788-1aa1-4722-9e4a-8fc492e66a3e.png">

When  phishing workflow is triggered using email attachment that contains an xls , it fails at the get sample by file hash atomic
This atomic point to target ThreatGrid_target which has https://panacea.threatgrid.com port 443
This used to work earlier
Can you please point to the correct authorization details, if account keys are now  required.

**Comment by mavander** [comment]
Hello!
The ThreatGrid/Secure Malware Analytics API key must be provided in a local variable in the workflow. Please see the documentation [here](https://ciscosecurity.github.io/sxo-05-security-workflows/workflows/email/0010-phishing-investigation#local-variables).
-Matt
