### ISSUE TITLE
Please update the workflows with the "Allow sensitive headers redirect" selected

### ISSUE THREAD

**Issue by pfiano** [CiscoSecurity/sxo-05-security-workflows#176]
Hi There,

Could you please update the workflows with the "Allow sensitive headers redirect" option selected in the HTTP requests that require so, for instance, the "Request category statistics" in the workflow n. 23

**Comment by mavander** [comment]
Workflows and atomic actions for Umbrella have been updated as needed. Note that the updated Umbrella atomics will appear for customers after the next Orchestration update in early August.
