### ISSUE TITLE
400 Bad Request - Umbrella - Excessive Requests to Incidents 

### ISSUE THREAD

**Issue by wezzlaren** [CiscoSecurity/sxo-05-security-workflows#186]
I use the default workflow (Umbrella - Excessive Requests to Incidents) in SecureX but I get a bad request at the "Request category statistics" step.  I did not change the threshold and categories. I have added my orgId.

In Postman the same API call is successful. I am unable to find out why this fails in SecureX. Any ideas?

{
  "output": {
    "error": {
      "code": "400",
      "message": "Failed to request report data from Umbrella\n\nStatus code: 400\nResponse body: {\n  \"message\":\"Bad request\"\n}"
    },
    "response": {
      "elapsed_time": 0.008448618,
      "end_time": "2022-08-15T11:35:10.342Z",
      "start_time": "2022-08-15T11:35:10.334Z",
      "succeeded": false
    }
  }
}

**Comment by mavander** [comment]
Hi @wezzlaren -
I just imported the workflow and ran it successfully. How long ago did you import the workflow? We released an update on July 25th which fixed an issue with HTTP headers not being forwarded properly. Maybe you need to import the latest version?

If you already have the latest version, I would suggest validating that your organization ID is correct and then check your targets and account keys. Information about how the targets/account keys should be configured can be found in the workflow's [documentation](https://ciscosecurity.github.io/sxo-05-security-workflows/workflows/umbrella/0023-excessive-requests-to-incident).

I'll leave this open until the end of the week, if I don't hear back I'll close the issue.

-Matt

**Comment by wezzlaren** [comment]
Hi @mavander  

Thank you for your reply!

After checking the documentation,  I noticed that I misconfigured the account keys.

The workflow is running successfully now :)
