### ISSUE TITLE
Use a Remote with the IMAP Endpoint Target Type

### ISSUE THREAD

**Issue by noname430** [CiscoSecurity/sxo-05-security-workflows#189]
It would be great if the Target Type `IMAP Endpoint` could be configured to use a Remote (similar to the `HTTP Endpoint` or `Terminal Endpoint`). This would help with the `Phishing Investigation` Workflow when IMAP is only made available on-premise.

**Comment by mavander** [comment]
Hi @noname430 -
I've relayed your suggestion to our product management team for them to submit/track as a feature request. Our goal is ultimately for the remote to support additional target types, so your vote for email targets has been noted :)
Thanks!
-Matt
