### ISSUE TITLE
Atomic Cisco PSIRT OpenVuln - Search Advisories By Severity missing pageIndex

### ISSUE THREAD

**Issue by aplukcisco** [CiscoSecurity/sxo-05-security-workflows#196]
Checking atomic Cisco PSIRT openVuln – Search Advisories by Severity, the atomic always return error about missing pageIndex.
 
When checking the actual API call, seems like the request is missing pageIndex param.
The API call used by atomic:
curl -X GET "https://api.cisco.com/security/advisories/severity/High/firstpublished?startDate=2022-01-01&endDate=2022-05-01&pageSize=100" -H "Content-Type: application/json" -H "Authorization: Bearer 3UI3lBHwLjNjNvBa3J7spnXsx02W"
 
The correct API call should be:
curl -X GET "https://api.cisco.com/security/advisories/severity/High/firstpublished?startDate=2022-01-01&endDate=2022-05-01&pageIndex=1&pageSize=100" -H "Content-Type: application/json" -H "Authorization: Bearer 3UI3lBHwLjNjNvBa3J7spnXsx02W"

**Comment by mavander** [comment]
Hello!
Thank you for reporting this. You are correct, if `pageSize` is provided, `pageIndex` is also required. This has been fixed and should be released with the next version SecureX orchestration (on/around October 14).
-Matt
