### ISSUE TITLE
Support for IPv6 when connecting to appliances

### ISSUE THREAD

**Issue by aplukcisco** [CiscoSecurity/sxo-05-security-workflows#197]
This is probably across the board for Targets setting in AO, not sure if we support IPv6. 

For example, when checking the Secure Firewall – Get Access Token atomic, the request it sent was: 
https://2001:420:2854:2013::58/api/fmc_platform/v1/auth/generatetoken
 
However the actual request should be 
https://[2001:420:2854:2013::58]/api/fmc_platform/v1/auth/generatetoken
 
This is because when using IPv6, we need the square brackets around the IP in the URL, since the request is missing the square brackets, so user won't be able to get access token from FMC if it is configured to use IPv6.

**Comment by mavander** [comment]
Hello!
IPv6 is not currently supported. I checked with engineering and am told that IPv6 support is on the roadmap, but we can't comment on any specific timeline at this point.
-Matt
