### ISSUE TITLE
Atomic Webex – Create Room should only require room title

### ISSUE THREAD

**Issue by aplukcisco** [CiscoSecurity/sxo-05-security-workflows#198]
Trying to run the Webex – Create Room atomic, it failed to create a room if only room title is provided. According to the Webex doc, room title should be the only required parameter. https://developer.webex.com/docs/api/v1/rooms/create-a-room
 
When I run the atomic with only room title provided, notice the teamId is set to “” in the body:
{
  "title": "Test Room",
  "teamId": ""
}
 
And it returns error:
{
  "output": {
    "activity_status": "Success",
    "response": {
      "elapsed_time": 0.131593704,
      "end_time": "2022-05-31T18:27:21.23Z",
      "error": {
        "code": "200",
        "message": "success"
      },
      "response_body": "{\"message\":\"The requested resource could not be found.\",\"errors\":[{\"description\":\"The requested resource could not be found.\"}],\"trackingId\":\"ROUTER_62965DE3-DA36-01BB-5E0A-AC12DE1F5E0A\"}",
      "response_headers": [
        {
          "name": "Server",
          "value": "Redacted"
        },
        {
          "name": "Content-Type",
          "value": "application/json"
        },
        {
          "name": "Connection",
          "value": "keep-alive"
        },
        {
          "name": "Via",
          "value": "1.1 linkerd, 1.1 linkerd"
        },
        {
          "name": "Trackingid",
          "value": "ROUTER_62965DE3-DA36-01BB-5E0A-AC12DE1F5E0A"
        },
        {
          "name": "Strict-Transport-Security",
          "value": "max-age=63072000; includeSubDomains; preload"
        },
        {
          "name": "Date",
          "value": "Tue, 31 May 2022 18:27:21 GMT"
        }
      ],
      "start_time": "2022-05-31T18:27:21.099Z",
      "status_code": 404,
      "status_text": "404 Not Found",
      "succeeded": true
    }
  }
}

**Comment by mavander** [comment]
Hello!
Thank you for reporting this. This has been fixed and should be released with the next version SecureX orchestration (on/around October 14).
-Matt
