### ISSUE TITLE
0013 - Secure Firewall - Impact Red Remediation

### ISSUE THREAD

**Issue by aledipas** [CiscoSecurity/sxo-05-security-workflows#199]
Currently when running this workflow, if there are no qualifying impact red incidents found by the workflow you will run into a failure to process some logic on the "Convert observables to table" step, screenshot and output provided:

![image](https://user-images.githubusercontent.com/77990864/189373705-4d608c1e-5029-4102-9231-0012b2199c2f.png)

![image](https://user-images.githubusercontent.com/77990864/189373751-b5154920-b724-4339-a19d-4a603f322807.png)

I would also like some guidance on generating impact red incidents to validate the workflows functionality as well.

Thanks!

**Comment by mavander** [comment]
This has been fixed
