### ISSUE TITLE
Improvement with webex team group

### ISSUE THREAD

**Issue by pfiano** [CiscoSecurity/sxo-05-security-workflows#20]
I would suggest an improvement when it comes to the time in the workflow to publish a message in webex teams. In fact, at this point in time, if the room does not exist, the workflow skips that part. I would suggest that first, it checks if the room already exists, if not, then it creates it. I have done it in my Talos Roundup Weekly Investigation workflow and it works smoothly.

**Comment by mavander** [comment]
Hi @pfiano -
Creating a Webex Teams room from within the workflow is out of scope. We have a `Webex Teams - Create Room` atomic people can use if they want to add this functionality in their instance.
-Matt
