### ISSUE TITLE
Atomic Secure Cloud Analytics - Remove Domain from Watchlist

### ISSUE THREAD

**Issue by tjbusch** [CiscoSecurity/sxo-05-security-workflows#200]
The Secure Cloud Analytics Remove Domain for Watchlist atomic has a logic error within the last "Was the request successful No check"

THe logic matches when the response is not equal to a 200 OK. Considered SCA will only return a 204 (https://swc-securex.obsrvbl.com/api/docs/#operation/deleteDomains) this check will always return True leading this No logic to match and cause a failure. This logic check should be changed from a 200 to a 204 to fix the issue. 

<img width="1409" alt="Screen Shot 2022-09-12 at 8 03 56 AM" src="https://user-images.githubusercontent.com/63874538/189648631-fa103f97-4738-4c34-a01b-b531f9930acc.png">

**Comment by mavander** [comment]
Hello!
Thank you for reporting this. This has been fixed and should be released with the next version SecureX orchestration (on/around October 14).
-Matt
