### ISSUE TITLE
Atomic Duo - Auth - Authenticate

### ISSUE THREAD

**Issue by tjbusch** [CiscoSecurity/sxo-05-security-workflows#201]
When using the Duo Auth API with a factor besides "passcode" the device parameter is required to be added to the request. When used with the factor passcode, this parameter must be removed otherwise the DUO Auth endpoint will return a 400 error as the device parameter is not supported with the passcode factor. 

Due to how the atomic is written as making the device variable a required object even setting the variable to  "" will result in the parameter being inserted into the request and failing. 
https://duo.com/docs/authapi#/auth

An easy fix to have this is to add a check that omits the device logic if the factor is = to passcode similar to the logic used in lines 15-17 of the generate function block. 

<img width="1503" alt="Screen Shot 2022-09-12 at 8 09 31 AM" src="https://user-images.githubusercontent.com/63874538/189650450-e7721e24-db79-4f95-81aa-1037bcd5daf8.png">

**Comment by mavander** [comment]
Hello!
Thank you for reporting this. This has been fixed and should be released with the next version SecureX orchestration (on/around October 14).
-Matt
