### ISSUE TITLE
Oauth authentication

### ISSUE THREAD

**Issue by jokern64** [CiscoSecurity/sxo-05-security-workflows#206]
Hi, a couple of orchestration examples on how to connect to a web service which uses Oauth2 would be great.
As with Oauth2 you also have many different methods and you need to use redirect URLS
https://ciscosecurity.github.io/sxo-05-security-workflows/activities/http-request/authentication

**Comment by mavander** [comment]
Hello!
OAuth implementations aren't all the same, so we're not able to document them in detail. I did, however, update the HTTP authentication page with more information about how OAuth typically works and what we do/don't support. The best thing to do is refer to the product API's documentation and then emulate their authentication process using `HTTP Request` activities. The updated page is at the same location [here](https://ciscosecurity.github.io/sxo-05-security-workflows/activities/http-request/authentication#oauth).
-Matt
