### ISSUE TITLE
Mods for - 0019 - Meraki MX - L3 Outbound Firewall Block

### ISSUE THREAD

**Issue by tekgourou** [CiscoSecurity/sxo-05-security-workflows#211]
I created a new version of this 0019 workflow to be able to add block IP to all or selected ORG and to all or selected NETWORK with MX. I have also add errors logs output.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/3695374/199073028-950e7fa3-d662-4ce1-9d63-cd7231daa316.png">[0019 - Meraki - MX - L3 Outbound Firewall Block (1).json.zip]
[Meraki - MX - L3 Outbound Firewall Block v2.json.zip](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/9903550/Meraki.-.MX.-.L3.Outbound.Firewall.Block.v2.json.zip)

**Comment by mavander** [comment]
Hello!

An updated version of workflow 0019 has been published with support for multiple organizations and networks.

-Matt
