### ISSUE TITLE
0029 - ISE - Add Endpoint to Identity Group – Fails when updating an Endpoint's Identity Group

### ISSUE THREAD

**Issue by SilverAmadeus** [CiscoSecurity/sxo-05-security-workflows#214]
The `0029 - ISE - Add Endpoint to Identity Group` workflow is using the Identity Groups's name in the Atomic `ISE - ERS - Endpoint - Update Identity Group`

![Screen Shot 2022-11-03 at 11 04 30](https://user-images.githubusercontent.com/11589555/199788812-6e16c0d8-dacc-444c-8086-349045d585c6.png)

 Which causes ISE's ERS API to fail with: 

``` 
id: 0215U00PSQLEE4ApjJkrMQ5OmEDazduYgCB, wf_instance_id: 0215U0050GONT1njWsRrUSOBDm9lgCq35fb, error: Failed to update the requested endpoint's identity group assignment

Status code: 500
Response body:
{
   "ERSResponse":{
      "operation":"PUT-update-endpoint",
      "messages":[
         {
            "title":"UPDATE: DB internal error during CRUD operation com.cisco.cpm.nsf.txmgmt.NSFTransactionException: com.cisco.epm.edf2.exceptions.EDF2SQLException: ORA-02291: integrity constraint (CEPM.REF_ROLE_MASTER) violated - parent key not found\n",
            "type":"ERROR",
            "code":"CRUD operation exception"
         }
      ],
      "link":{
         "rel":"related",
         "href":"https://192.168.10.20:9060/ers/config/endpoint/906508c0-4b2f-11ed-bd36-82ac1487010c",
         "type":"application/xml"
      }
   }
}
```

The workflow should use the Identity Group's ID in the `ISE - ERS - Endpoint - Update Identity Group` Atomic, like so…

<img width="443" alt="Screen Shot 2022-11-03 at 10 45 27" src="https://user-images.githubusercontent.com/11589555/199789307-a4bbd2d7-be4f-41c2-94b4-de12bc530329.png">

### How to reproduce:
1. Import the workflow.
2. Use an existing Mac

**Comment by mavander** [comment]
This has been fixed, thank you!
-Matt
