### ISSUE TITLE
0033 - SNA - Block External Threats With Umbrella variable reference typo

### ISSUE THREAD

**Issue by tjbusch** [CiscoSecurity/sxo-05-security-workflows#215]
Within the Add Destination To Blocked List block of the workflow the new value references the $workflow.SWE - Block Top  Extenal Alarming Host .local.ListofBlockedItems$ variable which appears to be a typo to the correct variable link $workflow.SWE - Block Top  External Alarming Host .local.ListofBlockedItems$

<img width="1571" alt="Screen Shot 2022-11-04 at 10 00 43 AM" src="https://user-images.githubusercontent.com/63874538/199992845-585cc828-6551-428c-bc19-b3334551b15e.png">

**Comment by mavander** [comment]
Thanks for letting us know about this. That variable reference is completely corrupt somehow, but I've fixed it.
-Matt
