### ISSUE TITLE
0002-Talos-SingleBlogPostToCTRCasebook__definition_workflow error

### ISSUE THREAD

**Issue by lastemist** [CiscoSecurity/sxo-05-security-workflows#220]
Hi when I test the worflowf I get an error on Threat Response - Inspect for Observables.
Error Code 400

id: 021ITC6RLFA3S7CWAEaK0XkJ3IECxS7zXeg, wf_instance_id: 021ITC6EAX01W2HBRdUxDRln1eJbHhTQMub, error: Failed to inspect content

Status code: 401
Response body: {"error":"invalid_request","error_description":"No JWT found in HTTP Authorization header"}

Tested with this url: https://blog.talosintelligence.com/avoslocker-new-arsenal/

I don't know If I'm doing fine.
Thaks

**Comment by mavander** [comment]
Hello!

This error usually means something isn't configured properly with your targets or account keys. Please see the workflow's [documentation](https://ciscosecurity.github.io/sxo-05-security-workflows/workflows/talos/0002-single-post-casebook) for a list of targets/account keys and how they should be configured. The latest version of this workflow uses a SecureX Token. If you aren't familiar with these or aren't sure if you have one, please have a look at [this page](https://ciscosecurity.github.io/sxo-05-security-workflows/account-keys/securex-token).

Unfortunately, we can't offer full technical support through Github issues. If you continue to have issues with this workflow, please contact [Cisco TAC](https://support.cisco.com/) for further assistance.

-Matt
