### ISSUE TITLE
Workflow to use SXO to extract Microsoft IPs and update SNA Host Group.

### ISSUE THREAD

**Issue by zooz211** [CiscoSecurity/sxo-05-security-workflows#226]
This workflow contacts a Microsoft URL which publishes the IPs and URLs of all Microsoft Office365 Services. The workflow will then extract the list of IPv4 and IPv6 addresses and add them to the "Trusted Interent Hosts" Host Group on Secure Network Analytics. 

Target Group: Default TargetGroup

Targets Used: SNA via SxO Remote

Steps:
[] Input the Username and Password for the SNA Management Center API User and choose the Host Group that will be used (Host Group Name must be an exact match to what is configured on the SMC).
[] Fetch the JSON output of all Microsoft O365 from the URL and extract all IPv4 and IPv6 addresses into a List.
[] Login to the SNA Management Center and request a session and XSRF token.
[] Request the Tenent List from SNA to get the Domain Name and ID.
[] Get a list of all Host Groups in the SMC for a given Domain ID
[] Extract the Host Group ID
[] Add the list of Microsoft IPs to the chosen Host Group
[SNA Published WF.txt](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/10518454/SNA.Published.WF.txt)

**Comment by mavander** [comment]
Thanks for the submission! The workflow has been standardized and published.

-Matt
