### ISSUE TITLE
0002 - Talos - Single Blog Post To SecureX Casebook: False Positives Casebooks created

### ISSUE THREAD

**Issue by pfiano** [CiscoSecurity/sxo-05-security-workflows#229]
I would also suggest that the 0002 workflow gets updated to discard sightings coming from Threat Intelligence sources otherwise you will easily get created "false positives" Casebooks for that reason. I have modified the workflow for my customers to include an exclusion string variable for (currently populated with SecureX Global Threat Intelligence, Talos Intelligence, AMP File Reputation modules), and then do a conditional checking, if the sighting(s) is/are coming from one of those modules, then I do skip. I have also updated the workflow to exclude sightings coming from certain domains like *talosintelligence* and *snort*, likely to create false positive casebooks.

**Comment by mavander** [comment]
Hi-
I've consulted with the product team and they don't think ignoring Threat Intelligence sources is a good idea. The better solution is to look at the `internal` field on the sightings, but unfortunately this field isn't always set by all SecureX sources. For now, we're going to leave the workflow as is.
-Matt
