### ISSUE TITLE
#0073 Secure Firewall: Block Observable (SSE) Webex error

### ISSUE THREAD

**Issue by ivanhern23** [CiscoSecurity/sxo-05-security-workflows#234]
Hello Matt, 

When trying to implement the #0073 Secure Firewall: Block Observable (SSE) I am getting the following error in the Atomic action "Webex - Search for Room":

_Status code: 401
Response body: {"message":"The request requires a valid access token set in the Authorization request header.","errors":[{"description":"The request requires a valid access token set in the Authorization request header."}],"trackingId":"ROUTER_63F5610D-40D2-01BB-7AF0-AC12D8757AF0"}_

**But when running the Atomic Action separately and independently of the Workflow with the exact same token it works just fine, and it's able to fetch the room name** 

-**Token, room ID and error for non-working scenario:**

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/113468060/220491356-c331e59e-b344-4f7c-b7e5-6273fa39335b.png">

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/113468060/220491437-13ddc863-7442-45f9-a191-8ad252dc22c1.png">

**-Working scenario using same variables but running the Atomic Action separately:**

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/113468060/220491805-03bb874e-defb-4ecc-ada7-4772efd77167.png">

**It seems that for some reason the Token in the workflow variable is not been passed to the atomic action correctly.**

Thanks for your help!
Regards
Ivan

**Comment by mavander** [comment]
Hello!

I checked the workflow and the Webex activities work as expected. All of the Webex atomics use the `Webex Access Token` local variable to get the access token. This local variable must be updated with your Webex token using the `Fetch Global Variables` activity at the beginning of the workflow. You can also update the local variable directly, but then you need to disable `Fetch Global Variables` or the local variable will be overwritten with nothing.

-Matt
