### ISSUE TITLE
Email target configuration.

### ISSUE THREAD

**Issue by ivanhern23** [CiscoSecurity/sxo-05-security-workflows#239]
Many of the workflows use the Email target to track down email inboxes, but the documentation on how to configure an Email Target is pretty austere.

In general the Target documentation should have more details on how to configure them, like destinations, addresses, ports etc.

**Comment by mavander** [comment]
Hello!

Are you referring to the documentation in Github (https://ciscosecurity.github.io/sxo-05-security-workflows/) or are you referring to the documentation in the product itself (https://docs.securex.security.cisco.com/Orchestration-Help/Content/targets.html)?

-Matt

**Comment by ivanhern23** [comment]
Hi Matt,

Targets, specifically.
(https://docs.securex.security.cisco.com/Orchestration-Help/Content/targets.html)

Regards!
Ivan

**Comment by mavander** [comment]
Got it! I've looked at the in-product docs and the instructions look fine to me. If you can be more specific about what information is missing or what you'd like to see added, I'd be happy to forward your feedback to the documentation team. I don't manage the in-product documentation personally.

-Matt
