### ISSUE TITLE
Talos - Blog RSS Feed to Threat Response Casebooks Run Error

### ISSUE THREAD

**Issue by oxsannikova** [CiscoSecurity/sxo-05-security-workflows#243]
I am getting an error with Talos - Blog RSS Feed to Threat Response Casebooks Run wf installed from My exchange.
<img width="1708" alt="Screenshot 2023-04-13 at 1 18 07 PM" src="https://user-images.githubusercontent.com/36735268/231875662-fc19e944-ebae-4cf7-bbde-a271354fd369.png">

**Comment by mavander** [comment]
Hi Oxana-

The version of the Talos blog workflow in Exchange is out of date. Please import the workflow from Github instead. We're in the process of removing/replacing the exchange content but are having some technical issues doing so. The workflows in Github should always be considered the gold standard version.

-Matt
