### ISSUE TITLE
WF Target needs to be updated for WF #0009

### ISSUE THREAD

**Issue by oxsannikova** [CiscoSecurity/sxo-05-security-workflows#244]
The WF Target is Orbital_For_Access_Token, while it needs to be CTR_For_Access_Token due to changed auth method for Orbital APIs.

https://github.com/CiscoSecurity/sxo-05-security-workflows/blob/Main/Workflows/0009-Orbital-CVEHuntToServiceNowIncident__definition_workflow_01FXZ5AS5EEEA4hWgDA7aGE0rSKFmygtRNc/definition_workflow_01FXZ5AS5EEEA4hWgDA7aGE0rSKFmygtRNc.json

**Comment by mavander** [comment]
Hi!

We're not updating workflows in this repository anymore, but we are going to start publishing workflows in the Cisco XDR automation exchange. We can add this workflow to the publishing list and as part of the publishing process we'll update the workflow to use the new targets.

-Matt
