### ISSUE TITLE
0001 workflow - talos blog - posts no longer containing IOCs

### ISSUE THREAD

**Issue by scottnishimura** [CiscoSecurity/sxo-05-security-workflows#246]
Hi Team,   
Seems sometime late last year, Talos Blog posts started changing the way they are mentioning IOCs in a post.  Instead of including it on the main page, there is now a link on the blog post to point to an external page (github, etc) where its now living.   I'm assuming due to some having a huge amount of IOCs this was done to alleviate the post size. 

This however is causing issues for our 0001 workflow that parses the blog post for the observables.   Being separated, the workflow can no longer report this.   Need to figure out a way around this whether to rebuild/design the workflow to look for these external links or to have Talos start publishing those IOCs on the main page again. 

thanks!

**Comment by sig666** [comment]
I also have same report from the customer. Our simple request is that expression format of Talos blog should be back to the original which have all the IoC in article with have new GitRepo IoC information. Please work with Talos?
