### ISSUE TITLE
Automatically Hide Secure X Ribbon.

### ISSUE THREAD

**Issue by chi2323** [CiscoSecurity/sxo-05-security-workflows#250]
Can the Security X Ribbon automatic hide,  It's in the way when I was doing screenshot!.  It either covering importance information or in middle of screenshot.   Now I have keep moving it left/right to avoid the problem.  It's very annoying! 

![image](https://github.com/CiscoSecurity/sxo-05-security-workflows/assets/30988066/566dea12-6dcf-4c1c-96ec-6a8a3d1d7359)

**Comment by mavander** [comment]
Hello!
This repository is strictly for issues related to SecureX orchestration. If you have an issue with another part of the product, you can contact Cisco TAC. If you're a Cisco employee and have a suggestion for the product, you can submit it [here](https://ciscosecurity.ideas.aha.io/ideas/new?project_id=6771886138183261677).
Thanks!
-Matt
