### ISSUE TITLE
Umbrella Workflow #17 note

### ISSUE THREAD

**Issue by ivanhern23** [CiscoSecurity/sxo-05-security-workflows#252]
Hi, 

As a side note, the Block Destination Lists in Umbrella do not support IP addresses, only the Allow lists, it would be good to add a note about this into the documentation of workflow #17, because when submitting the observable in the workflow, we don't receive any error, but the IP address doesn't appear in the block lists.

Thank you!
Iván

**Comment by mavander** [comment]
A note has been added to the workflow documentation for workflow 17.

Thanks!
