### ISSUE TITLE
Workflow to detect and delete duplicate hostnames on Cisco Secure Endpoint

### ISSUE THREAD

**Issue by vivsing4** [CiscoSecurity/sxo-05-security-workflows#253]
I have created two workflows one to **detect** duplicate hostnames and other to **delete** them.
This feature is currently only with TAC via support-portal and customer, if needed, has to open service-request to delete duplicates.

I have tested both workflows in our NAM TAC Support org successfully.
Below are their exported json files:
[Duplicate hostname detect.json.zip](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/12110486/Duplicate.hostname.detect.json.zip)
[Duplicate hostname delete.json.zip](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/12110487/Duplicate.hostname.delete.json.zip)

I am checking if it is feasible for us to make these workflows available to our customers via git repo.
Please feel free to reach out to me in case you have any queries.

**Comment by vivsing4** [comment]
Uploaded sanitised Workflows following best practices guidelines.

**Comment by vivsing4** [comment]
Here is the updated 'Detect' workflow which takes into account endpoints more than 500 and requests multiple API queries.
[Duplicate hostname detect.json.zip](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/12164780/Duplicate.hostname.detect.json.zip)

I am still working on 'Delete' workflow for this criteria. Will upload this one shortly.

**Comment by vivsing4** [comment]
Here is the updated 'Delete' workflow which takes into account endpoints more than 500 and requests multiple API queries.
[Duplicate hostname-delete.json.zip](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/12447039/Duplicate.hostname-delete.json.zip)

**Comment by mavander** [comment]
Hello!

Thank you for your submission. Due to the end of life announcement for Cisco SecureX, new content will not be published in this repository. We suggest keeping an eye on the new Cisco XDR automation exchange which may support community contribution in the future.

-Matt
