### ISSUE TITLE
Failed to resolve variable reference '$trigger.01NPWGRWOL9483e3NNaQ8N0STBNFXlMeXYF.output.attachments$'

### ISSUE THREAD

**Issue by SecOp187** [CiscoSecurity/sxo-05-security-workflows#31]
After configuring the Phishing Investigation Workflow, I am getting the following error message when running it at the
"For Each Attachment" step: [Failed to resolve variable reference '$trigger.01NPWGRWOL9483e3NNaQ8N0STBNFXlMeXYF.output.attachments$']. Is there an Event, Target or Variables misconfiguration done on my end?

Please advise.

**Comment by mavander** [comment]
Hi @SecOp187 -

This can happen if you change the workflow's trigger. You'll notice that the variable refers to the trigger's unique ID, so if that trigger no longer exists or was deleted/re-created the reference will be invalid. You can try fixing this by:
1. Click on the `For Each Attachment` loop
2. Change the `Source Array` variable to your new trigger's attachment's array. Like this:
![image](https://user-images.githubusercontent.com/62724342/115068527-60ceb100-9ec0-11eb-9874-c506a01cfd89.png)

Note that there are other parts of the workflow that refer to the trigger. You'll need to update them as well or you'll get the same error:
1. `Threat Response v2 - Create Sighting`
2. `Webex Teams - Post Message to Room`
3. `Send SOC notification` (left branch)
4. `Send update to reporting user`
5. `Send SOC notification` (right branch)
6. `Add row to statistics table`

Hope this helps.
-Matt

**Comment by SecOp187** [comment]
Hi @mavander 

Thank you for sharing your fix suggestion. I re-created the trigger and change the new trigger variables in all the activities but I am still getting the same error message:
`{
  "output": {
    "error": {
      "code": "BadRequest",
      "message": "Failed to resolve variable reference '$trigger.01NSG6POOIJ4D09LfXmG93JwFZLApqE1VLv.output.attachments$'"
    },
    "response": {
      "elapsed_time": 0.024428381,
      "end_time": "2021-04-16T20:12:30.406923955Z",
      "start_time": "2021-04-16T20:12:30.382495574Z",
      "succeeded": false
    }
  }
}`

**Comment by mavander** [comment]
Hi @SecOp187 -
Unfortunately, the level of support you'll need to fix broken variable references isn't something I can provide through GitHub issues. The workflow itself has worked for many others, so I suspect something is a bit funky in your copy of it. I'd recommend you contact [Cisco TAC](http://support.cisco.com/) for further assistance.
-Matt

**Comment by camcuoi** [comment]
I have the same issue. Since Cisco SecureX is free at the moment, I don't know how to open TAC case because the entitlement process requires me to provide serial number or support contract and I don't have that information.
@SecOp187  Have you been able to solve this issue ?

**Comment by mavander** [comment]
You can open a TAC case under whatever entitlement you're using to quality for SecureX. For example, if you have SecureX because of an entitlement for Cisco Secure Endpoint (formerly AMP), you can open a TAC case under Secure Endpoint and it can be routed to the SecureX team.

**Comment by SecOp187** [comment]
> I have the same issue. Since Cisco SecureX is free at the moment, I don't know how to open TAC case because the entitlement process requires me to provide serial number or support contract and I don't have that information. @SecOp187 Have you been able to solve this issue ?

Yes, I was able to resolve the issue and this is the resolution summary:
The work flow needs to trigger via email instead manual.

The issue is happening with mention work flow because it is expecting to run when there is an incoming email with an attachment on it, if you run the workflow manually (not through the email trigger) then the workflow will fail in resolving the email attachment simply because there is none. Hence this is an expected behavior.

====
As I have mention in my previous email, you need to trigger an email to the same mailbox for which you have configured the workflow. The mail should have an email as an attachment or an email with document as an attachment. Here is the Video Document as well.
 
Plz watch at 5:21 where he has mention that you can’t trigger the flow manually instead email trigger event. For more details about email trigger event.
https://ciscosecurity.github.io/sxo-05-security-workflows/events/email
 
 
https://www.youtube.com/watch?v=xUehFeCJGL4&list=PLPFIie48Myg2tu2gHbgm-moYg8LDaXsSo&index=8

Let me know if that helps.
