### ISSUE TITLE
Duplicate 0010 - Phishing Investigation Run Instances

### ISSUE THREAD

**Issue by SecOp187** [CiscoSecurity/sxo-05-security-workflows#39]
Hi,

We have noticed that SecureX run two Phishing investigation workflow instances for the same reported email. Can you please explain why this issue occurs and provide a solution?

![image](https://user-images.githubusercontent.com/82619023/117892686-05e56b00-b26e-11eb-94a4-9cbf031a7569.png)

![image](https://user-images.githubusercontent.com/82619023/117892771-2a414780-b26e-11eb-84a2-ecd3aa25f121.png)

Thank you,
Delvain

**Comment by mavander** [comment]
This can happen if you have two triggers for the same workflow or two copies of the workflow with the same trigger. Are you sure nothing has been duplicated in your orchestration instance?

**Comment by SecOp187** [comment]
Hi Matt,

I have one trigger based one event for the same workflow (see below). 
![image](https://user-images.githubusercontent.com/82619023/118179558-4f5ac500-b3ea-11eb-9b80-7988d9bfd457.png)
I have one copy of the Phishing Investigation workflow imported from the GitHub repository (see below)
![image](https://user-images.githubusercontent.com/82619023/118179911-c2643b80-b3ea-11eb-9a92-96e79e491bd6.png)
I am sure there's nothing that has been duplicated because this duplicate run instances occurs randomly for the same type of email. Additionally, Our email server only logs one forwarded email saved in the monitoring inbox. 

Let me know if you need me to send you the workflow (JSON) for further analysis.

Best,
Delvain

**Comment by mavander** [comment]
Hi @SecOp187 -

I spoke to engineering and they said this is more likely to be an issue with the orchestration engine than the workflows themselves. If you haven't already, please open a TAC case for this. Engineering wants to take a look at logs and will need your tenant information (which we don't collect in a public forum).

Thanks,
-Matt
