### ISSUE TITLE
This Workflow uses API calls only available in FMC 7.0

### ISSUE THREAD

**Issue by tdebruyn** [CiscoSecurity/sxo-05-security-workflows#51]
This workflow relies on atomics which uses API calls only available in FMC 7.0:
definition_workflow_01OGBAZGM3YMV0bqsLb2rkF0sHMbavxOE95 :
/api/fmc_config/v1/domain/{domainUUID}/object/dynamicobjects

https://www.cisco.com/c/en/us/td/docs/security/firepower/70/api/REST/firepower_management_center_rest_api_quick_start_guide_70/Objects_In_The_REST_API.html#Cisco_Reference.dita_5c21d27f-9f35-4de1-a4cc-461aa515ec29

It should be mentioned in the documentation:
https://ciscosecurity.github.io/sxo-05-security-workflows/workflows/secure-firewall/0031-microsoft-online-object-update

**Comment by mavander** [comment]
This has been fixed #53 . Thanks!
