### ISSUE TITLE
Workflow Analyzer incorrectly displays the  "Continue on HTTP error status code" checkbox status

### ISSUE THREAD

**Issue by AnastasiiaRozlyvan** [CiscoSecurity/sxo-05-security-workflows#52]
I'm trying to check the atomic for compliance with best practices, and the "Continue on HTTP error status code" is checked. (As you can see in the picture.)
![Screenshot 2021-06-16 at 10 14 50](https://user-images.githubusercontent.com/48979187/122174871-ca047d80-ce8b-11eb-905e-370af51f9473.png)
However, when doing validation, I get the following message. ↓
![Screenshot 2021-06-16 at 10 16 26](https://user-images.githubusercontent.com/48979187/122174990-eaccd300-ce8b-11eb-82e6-15360536a265.png)
It looks like a bug in Workflow Analyzer.

**Comment by mavander** [comment]
Thank you for reporting this, it should be fixed in the latest version! (you may need to clear your cache for the javascript to update)
