### ISSUE TITLE
Workflow Analyzer Continue Workflow Execution on Failure warning

### ISSUE THREAD

**Issue by MaxMhonc** [CiscoSecurity/sxo-05-security-workflows#57]
Hello Team,

I'm trying to use an HTTP request block and if the call target is off
I get a response without a status code. So I can't handle it with the help of the condition block that compares status codes.
![img1](https://user-images.githubusercontent.com/71133140/123270846-f01fc280-d508-11eb-8123-10df743a23e4.png)
![img2](https://user-images.githubusercontent.com/71133140/123270901-fada5780-d508-11eb-80fd-00d241cb5027.png)
I've handled it in the following way. I allowed "CONTINUE WORKFLOW EXECUTION ON FAILURE".
![img3](https://user-images.githubusercontent.com/71133140/123270955-062d8300-d509-11eb-9563-77ed26c6b858.png)
And then I used the condition block with two checks:
1) if the request block failed and 
2) if the status code is not 200.

It works. But when I used "Workflow Analyzer"
I got a warning "Continue Workflow Execution on Failure".
![img4](https://user-images.githubusercontent.com/71133140/123271041-1a718000-d509-11eb-9c3d-4f60f9305bd6.png)
Looks like "Workflow Analyzer" does not maintain cases like this and would be great if it did.

**Comment by mavander** [comment]
The guidance for "Continue Workflow Execution on Failure" has been updated for HTTP Requests in #60 . It's now informational instead of a warning and the details have been expanded to be more helpful
