### ISSUE TITLE
Notification email message is not populate with the subject of the original message to be investigate

### ISSUE THREAD

**Issue by tekgourou** [CiscoSecurity/sxo-05-security-workflows#8]
hi, 
I notice that the subject in the message body of the notification email back to the user is not populate with the original subject of the investigated email. Thanks to look at this.

**Comment by mavander** [comment]
[Issue Location](https://github.com/CiscoSecurity/sxo-05-security-workflows/blob/66c9e5b0ecdaffc98e333cc40d95d433eea9a0a0/Workflows/0010-Phishing-Investigation__definition_workflow_01LDICSCPVGP20hFTpJfjEVUZ57FMXx5sOC/definition_workflow_01LDICSCPVGP20hFTpJfjEVUZ57FMXx5sOC.json#L683)

Instances of:
`$trigger.triggerevent_01LDICT231ZS43miaxKIy0SEERAAMo7ddn6.output.subject$`

Should probably be replaced with:
`$workflow.definition_workflow_01LDICSCPVGP20hFTpJfjEVUZ57FMXx5sOC.local.variable_workflow_01LG4CXZB1PS85vMbaUCSTf8j02SCyIImgV$`

Will look into this and publish an update.

**Comment by mavander** [comment]
@tekgourou -
I've updated the workflow to use the subject of the reported email where possible. See [this commit](https://github.com/CiscoSecurity/sxo-05-security-workflows/commit/552187ecb74178f9c7ca3791231e6dbaaf65e125) and [this version](https://raw.githubusercontent.com/CiscoSecurity/sxo-05-security-workflows/552187ecb74178f9c7ca3791231e6dbaaf65e125/Workflows/0010-Phishing-Investigation__definition_workflow_01LDICSCPVGP20hFTpJfjEVUZ57FMXx5sOC/definition_workflow_01LDICSCPVGP20hFTpJfjEVUZ57FMXx5sOC.json) of the workflow. Would you like to test with the new version and confirm it addresses your concerns? Just keep in mind if you import this and overwrite your existing copy you will lose any changes you have made. You may want to import it as a copy, disable the trigger in your other copy, and enable the trigger on this one.
Let me know...
-Matt
